
CREATE TABLE ESTADOS(
	id_estado INTEGER PRIMARY KEY NOT NULL,
	nome_estado VARCHAR2(100)
);

CREATE TABLE CIDADE(
	id_cidade INTEGER PRIMARY KEY NOT NULL,
	id_estado INTEGER NOT NULL,
	nome_cidade VARCHAR2(100),
	CONSTRAINT FK_ID_ESTADO FOREIGN KEY (id_estado) REFERENCES ESTADOS(id_estado)
);

CREATE TABLE ENDERECO(
	id_endereco INTEGER PRIMARY KEY NOT NULL,
	id_cidade INTEGER NOT NULL,
	cep VARCHAR2(8) NOT NULL UNIQUE,
	numero NUMERIC NOT NULL,
	logradouro VARCHAR2(220),
	CONSTRAINT FK_ID_CIDADE FOREIGN KEY (id_cidade) REFERENCES CIDADE(id_cidade)
);

CREATE TABLE HOTEIS(
	id_hotel INTEGER PRIMARY KEY NOT NULL,
	id_endereco INTEGER NOT NULL,
	nome VARCHAR2(120) NOT NULL,
	CONSTRAINT FK_ID_ENDERECO FOREIGN KEY (id_endereco) REFERENCES ENDERECO(id_endereco)
);

CREATE TABLE QUARTOS(
	id_quartos INTEGER PRIMARY KEY NOT NULL,
	id_hotel INTEGER NOT NULL,
	numero_quarto NUMERIC NOT NULL,
	valor_diaria NUMBER(10,4),
	CONSTRAINT FK_ID_HOTEIS FOREIGN KEY (id_hotel) REFERENCES HOTEIS(id_hotel)
);


-- ########################################################################################


CREATE TABLE USUARIO(
	id_usuario INTEGER PRIMARY KEY NOT NULL,
	nome VARCHAR2(120) NOT NULL,
	cpf VARCHAR2(11) UNIQUE NOT NULL,
	data_nascimento DATE NOT NULL,
	login VARCHAR2(120) NOT NULL,
	senha VARCHAR2(120) NOT NULL,
	tipo_usuario INTEGER NOT NULL	
);

CREATE TABLE RESERVA(
	id_reserva INTEGER PRIMARY KEY NOT NULL,
	id_hotel INTEGER NOT NULL,
	id_quartos INTEGER NOT NULL,
	id_usuario INTEGER NOT NULL,
	data_reserva DATE NOT NULL,
	CONSTRAINT FK_HOTEL_RESERVA FOREIGN KEY (id_hotel) REFERENCES HOTEIS(id_hotel),
	CONSTRAINT FK_QUARTO_RESERVA FOREIGN KEY (id_quartos) REFERENCES QUARTOS(id_quartos),
	CONSTRAINT FK_USUARIO_RESERVA FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);


-- ######################## SEQUENCES #########################
CREATE SEQUENCE SEQ_ESTADOS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_CIDADES
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_ENDERECOS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_HOTEIS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_QUARTOS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_RESERVAS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_USUARIO
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_ESTADOS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;


-- ######################## INSERTS ########################

INSERT INTO ESTADOS VALUES (SEQ_ESTADOS.NEXTVAL, 'RIO GRANDE DO SUL');
INSERT INTO ESTADOS VALUES (SEQ_ESTADOS.NEXTVAL, 'SÃO PAULO');
INSERT INTO ESTADOS VALUES (SEQ_ESTADOS.NEXTVAL, 'PERNAMBUCO');

INSERT INTO CIDADE VALUES (SEQ_CIDADES.NEXTVAL,  1, 'PORTO ALEGRE');
INSERT INTO CIDADE VALUES (SEQ_CIDADES.NEXTVAL,  1, 'GRAMADO');

INSERT INTO CIDADE VALUES (SEQ_CIDADES.NEXTVAL,  2, 'SÃO PAULO');
INSERT INTO CIDADE VALUES (SEQ_CIDADES.NEXTVAL,  2, 'GUARATINGUETA');

INSERT INTO CIDADE VALUES (SEQ_CIDADES.NEXTVAL,  3, 'RECIFE');
INSERT INTO CIDADE VALUES (SEQ_CIDADES.NEXTVAL,  3, 'OLINDA');

INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 1, '96523031', 105, 'Av. Severo Dullius');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 1, '96659441', 2003, 'Av. Icarai');

INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 2, '75693662', 115, 'Av. Ipiranga');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 2, '76533987', 255, 'Av. Guanabara');

INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 3, '36559998', 855, 'Protásio Alves');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 3, '69898886', 255, 'Simão Bolivar');

INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 4, '12336659', 5, 'Av. JK');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 4, '12898886', 300, 'Av. João Pessoa');

INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 5, '45665978', 12, 'Av. Boa Viagem');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 5, '12820086', 78, 'Av. João de Barros');

INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 6, '45000078', 14, 'Av. Dantas Barreto');
INSERT INTO ENDERECO VALUES (SEQ_ENDERECOS.NEXTVAL, 6, '12829686', 198, 'Av. Principal');

INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 1, 'Novo Hotel');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 2, 'Velho Hotel');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 3, 'Jafoi Hotel');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 4, 'Hotel JK');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 5, 'Bela Vista');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 9, 'Ibis');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 10, 'Plaza');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 11, 'Hotel da Rainha');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 12, 'Hotel do Rei');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 13, 'Hotel do Papa');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 14, 'Hotel dos Guri');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 15, 'Hotel Lotus');


INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 1, 100, 300.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 1, 122, 370.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 2, 221, 150.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 2, 233, 186.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 3, 444, 275.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 3, 552, 450.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 4, 322, 199.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 4, 125, 299.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 5, 600, 366.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 5, 678, 257.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 6, 198, 398.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 6, 720, 247.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 7, 912, 233.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 7, 478, 799.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 8, 962, 480.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 8, 111, 398.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 9, 333, 150.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 9, 444, 450.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 10, 458, 300.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 10, 659, 326.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 11, 746, 415.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 11, 922, 310.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 12, 652, 320.00);
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 12, 122, 383.00);

SELECT  * FROM RESERVA r 
SELECT * FROM USUARIO u 
SELECT * FROM QUARTOS q 
INSERT INTO USUARIO 
	VALUES (SEQ_USUARIO.NEXTVAL, 'Usuario Teste', '32669889780', TO_DATE('30-01-1978', 'dd-mm-yyyy'), 'teste', 'teste123', 0)

INSERT INTO RESERVA 
	VALUES (SEQ_RESERVAS.NEXTVAL, 1, 1, 1, TO_DATE('21-10-2021', 'dd-mm-yyyy'))

INSERT INTO RESERVA 
	VALUES (SEQ_RESERVAS.NEXTVAL, 2, 2, 1, TO_DATE('21-10-2021', 'dd-mm-yyyy'))


SELECT r.ID_RESERVA, h.NOME, q.numero_quarto FROM RESERVA r 
	LEFT JOIN HOTEIS h ON (r.ID_HOTEL = h.ID_HOTEL)	
	LEFT JOIN QUARTOS q ON (q.ID_QUARTOS = r.ID_QUARTOS)


SELECT * FROM QUARTOS q WHERE ID_HOTEL = 2
