
CREATE TABLE ESTADOS(
	id_estados INTEGER PRIMARY KEY NOT NULL,
	nome_estados VARCHAR2(100)
);

CREATE TABLE CIDADES(
	id_cidades INTEGER PRIMARY KEY NOT NULL,
	id_estados INTEGER NOT NULL,
	nome_cidades VARCHAR2(100),
	CONSTRAINT FK_ID_ESTADOS FOREIGN KEY (id_estados) REFERENCES ESTADOS(id_estados)
);

CREATE TABLE ENDERECOS(
	id_enderecos INTEGER PRIMARY KEY NOT NULL,
	id_cidades INTEGER NOT NULL,
	logradouro VARCHAR2(255) NOT NULL,
	numero_enderecos INTEGER NOT NULL,
	cep VARCHAR2(9),
	CONSTRAINT FK_ID_CIDADES FOREIGN KEY (id_cidades) REFERENCES CIDADES(id_cidades)
);

CREATE TABLE HOTEIS(
	id_hoteis INTEGER PRIMARY KEY NOT NULL,
	id_enderecos INTEGER NOT NULL,
	nome VARCHAR2(120) NOT NULL,
	CONSTRAINT FK_ID_ENDERECOS FOREIGN KEY (id_enderecos) REFERENCES ENDERECOS(id_enderecos)
);

CREATE TABLE QUARTOS(
	id_quartos INTEGER PRIMARY KEY NOT NULL,
	id_hoteis INTEGER NOT NULL,
	numero_quarto INTEGER NOT NULL,
	valor_diaria NUMBER(10,4),
	descricao VARCHAR2(50),
	CONSTRAINT FK_ID_HOTEIS FOREIGN KEY (id_hoteis) REFERENCES HOTEIS(id_hoteis)
);


-- ########################################################################################


CREATE TABLE USUARIO(
	id_usuario INTEGER PRIMARY KEY NOT NULL,
	nome VARCHAR2(120) NOT NULL,
	cpf VARCHAR2(11) UNIQUE NOT NULL,
	data_nascimento DATE NOT NULL,
	login VARCHAR2(120) NOT NULL,
	senha VARCHAR2(120) NOT NULL,
	tipo_usuario INTEGER NOT NULL
);

CREATE TABLE RESERVA(
	id_reserva INTEGER PRIMARY KEY NOT NULL,
	id_hoteis INTEGER NOT NULL,
	id_quartos INTEGER NOT NULL,
	id_usuario INTEGER NOT NULL,
	data_reserva DATE NOT NULL,
	CONSTRAINT FK_HOTEL_RESERVA FOREIGN KEY (id_hoteis) REFERENCES HOTEIS(id_hoteis),
	CONSTRAINT FK_QUARTO_RESERVA FOREIGN KEY (id_quartos) REFERENCES QUARTOS(id_quartos),
	CONSTRAINT FK_USUARIO_RESERVA FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);


-- ######################## SEQUENCES #########################
CREATE SEQUENCE SEQ_ESTADOS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_CIDADES
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_ENDERECOS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_HOTEIS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_QUARTOS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_RESERVAS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_USUARIO
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;


-- ######################## INSERTS ########################

SELECT * FROM HOTEIS

INSERT INTO ESTADOS VALUES (SEQ_ESTADOS.NEXTVAL, 'RIO GRANDE DO SUL');
INSERT INTO ESTADOS VALUES (SEQ_ESTADOS.NEXTVAL, 'SÃO PAULO');
INSERT INTO ESTADOS VALUES (SEQ_ESTADOS.NEXTVAL, 'PERNAMBUCO');

INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL,  1, 'PORTO ALEGRE');
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL,  1, 'GRAMADO');

INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL,  2, 'SÃO PAULO');
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL,  2, 'GUARATINGUETA');

INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL,  3, 'RECIFE');
INSERT INTO CIDADES VALUES (SEQ_CIDADES.NEXTVAL,  3, 'OLINDA');

INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 1, 'Av. Severo Dullius', 105,'96523-031');
INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 1, 'Av. Icarai',2003,'96659-441');

INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 2, 'Av. Ipiranga', 115, '75693-662');
INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 2, 'Av. Guanabara', 255,'76533-987');

INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 3, 'Protásio Alves', 855, '36559-998');
INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 3, 'Simão Bolivar', 255,'69898-886');

INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 4, 'Av. JK', 5,'12336-659');
INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 4, 'Av. João Pessoa', 300,'12898-886');

INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 5, 'Av. Boa Viagem', 12,'45665-978');
INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 5, 'Av. João de Barros', 78,'12820-086');

INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 6, 'Av. Dantas Barreto', 14,'45000-078');
INSERT INTO ENDERECOS VALUES (SEQ_ENDERECOS.NEXTVAL, 6, 'Av. Principal', 198,'12829-686');

INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 1, 'Novo Hotel');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 2, 'Velho Hotel');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 3, 'Jafoi Hotel');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 4, 'Hotel JK');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 5, 'Bela Vista');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 6, 'Ibis');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 7, 'Plaza');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 8, 'Hotel da Rainha');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 9, 'Hotel do Rei');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 10, 'Hotel do Papa');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 11, 'Hotel dos Guri');
INSERT INTO HOTEIS VALUES (SEQ_HOTEIS.NEXTVAL, 12, 'Hotel Lotus');


INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 1, 100, 300.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 1, 122, 370.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 2, 221, 150.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 2, 233, 186.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 3, 444, 275.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 3, 552, 450.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 4, 322, 199.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 4, 125, 299.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 5, 600, 366.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 5, 678, 257.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 6, 198, 398.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 6, 720, 247.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 7, 912, 233.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 7, 478, 799.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 8, 962, 480.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 8, 111, 398.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 9, 333, 150.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 9, 444, 450.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 10, 458, 300.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 10, 659, 326.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 11, 746, 415.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 11, 922, 310.00,'Solteiro');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 12, 652, 320.00,'Casal');
INSERT INTO QUARTOS VALUES (SEQ_QUARTOS.NEXTVAL, 12, 122, 383.00,'Solteiro');


INSERT INTO USUARIO
	VALUES (SEQ_USUARIO.NEXTVAL, 'Usuario Teste', '32669889780', TO_DATE('30-01-1978', 'dd-mm-yyyy'), 'teste', 'teste123', 0)

INSERT INTO RESERVA
	VALUES (SEQ_RESERVAS.NEXTVAL, 1, 1, 1, TO_DATE('21-10-2021', 'dd-mm-yyyy'))

INSERT INTO RESERVA
	VALUES (SEQ_RESERVAS.NEXTVAL, 2, 3, 1, TO_DATE('21-10-2021', 'dd-mm-yyyy'))

	SELECT r.ID_RESERVA, h.NOME, q.numero_quarto, q.valor_diaria,Q.DESCRICAO FROM RESERVA r
	LEFT JOIN HOTEIS h ON (r.ID_HOTEIS = h.ID_HOTEIS)
	LEFT JOIN QUARTOS q ON (q.ID_QUARTOS = r.ID_QUARTOS)


	SELECT seq_usuario.nextval mysequence from DUAL
